# Generated by Django 6.0.6 on 2026-06-14 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelOptions(
            name="postcategory",
            options={
                "verbose_name": "Категория поста",
                "verbose_name_plural": "Категории постов",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="rating",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_category",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_of_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_of_comment",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="link_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="news.post",
                verbose_name="Пост",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating_of_comment",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="news.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                through="news.PostCategory",
                to="news.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="choice",
            field=models.CharField(
                choices=[("AR", "Статья"), ("NW", "Новость")],
                default="AR",
                max_length=2,
                verbose_name="Вид поста",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="data_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="post",
            name="rating_of_post",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text_of_post",
            field=models.TextField(verbose_name="Текст поста"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_of_post",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="news.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="news.post",
                verbose_name="Пост",
            ),
        ),
    ]
