# Generated by Django 6.0.6 on 2026-06-15 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчики",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_category",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название категории"
            ),
        ),
    ]
